import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Sign Up to control your database",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="h-screen w-screen flex flex-col gap-4 items-center justify-center">
          <h1 className="text-2xl text-center">
            {" "}
            TEST PAGE THAT INVOKES DB OPERATIONS etc.
          </h1>
          {children}
        </div>
      </body>
    </html>
  );
}
